import Link from "next/link";
import { Logo } from "./site-shell";
import { PartnerCarousel, type PartnerBrand } from "./partner-carousel";

type CountryKey="sri-lanka"|"bangladesh"|"maldives"|"dubai";
const countries:{key:CountryKey;name:string;route:string;code:string;flag:string}[]=[
  {key:"sri-lanka",name:"Sri Lanka",route:"/sri-lanka",code:"LK",flag:"/flags/lk.png"},{key:"bangladesh",name:"Bangladesh",route:"/bangladesh",code:"BD",flag:"/flags/bd.png"},
  {key:"maldives",name:"Maldives",route:"/maldives",code:"MV",flag:"/flags/mv.png"},{key:"dubai",name:"Dubai",route:"/dubai",code:"AE",flag:"/flags/ae.png"},
];
const data={
  "sri-lanka":{place:"Sri Lanka",eyebrow:"Sri Lanka commercial kitchen specialists",headline:<>Commercial<br/>kitchens.<br/><em>Engineered<br/>to perform.</em></>,intro:"TGF plans, designs, supplies, installs and supports future-ready foodservice environments for hospitality, healthcare, commercial and institutional operations.",projects:[["Hilton Yala","Complete FOH & BOH kitchen equipment","/project-hilton-yala.png"],["Hilton Colombo","Complete FOH & BOH kitchen equipment","/project-hilton-colombo.png"],["Hilton Weerawila","Design, supply & FOH installation","/project-hilton-weerawila.png"]]},
  bangladesh:{place:"Bangladesh",eyebrow:"Foodservice solutions for Bangladesh",headline:<>Hospitality<br/>kitchens.<br/><em>Built for<br/>scale.</em></>,intro:"Engineering-led planning, equipment supply, installation and long-term technical support for hospitality, healthcare, commercial and institutional foodservice.",projects:[["Hospitality kitchens","Bangladesh portfolio"],["Healthcare foodservice","Bangladesh portfolio"],["Commercial kitchens","Bangladesh portfolio"],["Institutional kitchens","Bangladesh portfolio"]]},
  maldives:{place:"Maldives",eyebrow:"Island hospitality expertise",headline:<>Resort<br/>kitchens.<br/><em>Designed for<br/>island life.</em></>,intro:"Globally benchmarked kitchen systems, dependable equipment and after-sales care tailored to remote island hospitality and resort operations.",projects:[["W Maldives","FOH & BOH kitchen equipment","/project-w-maldives.png"],["Le Méridien Maldives Resort & Spa","Complete FOH & BOH kitchen equipment","/project-le-meridien-maldives.png"]]},
  dubai:{place:"Dubai",eyebrow:"Commercial kitchens for the UAE",headline:<>High-performance<br/>kitchens.<br/><em>Ready for<br/>ambition.</em></>,intro:"Technically rigorous, efficient and future-ready foodservice solutions shaped around the operational demands of the UAE hospitality market.",projects:[["Hospitality kitchens","UAE portfolio"],["Healthcare foodservice","UAE portfolio"],["Commercial kitchens","UAE portfolio"],["Institutional kitchens","UAE portfolio"]]},
} as const;
const services=[["Planning & kitchen design","FCSI-aligned planning shaped around workflow, ergonomics, safety and operational efficiency."],["Equipment supply & installation","Globally reputed equipment specified, supplied and installed for reliable long-term performance."],["Fabrication & infrastructure","Commercial kitchen fabrication and infrastructure solutions engineered for real operating conditions."],["Workflow optimisation","Future-ready systems that integrate equipment, technology and sustainable operational practices."],["After-sales support","Internationally trained technical expertise providing dependable service throughout the equipment lifecycle."]];
const normalizedLogo=(filename:string)=>`/logos/normalized/${filename}.png`;
const partners:readonly PartnerBrand[]=[["Fagor",normalizedLogo("partner-27")],["Moffat",normalizedLogo("partner-28")],["Mareno",normalizedLogo("partner-29")],["Trutee",normalizedLogo("partner-30")],["Rational",normalizedLogo("partner-31")],["UNOX",normalizedLogo("partner-32")],["Williams",normalizedLogo("partner-33")],["Precision",normalizedLogo("partner-34")],["Hobart",normalizedLogo("partner-35")],["Sammic",normalizedLogo("partner-36")],["Roller Grill",normalizedLogo("partner-37")],["Bartscher",normalizedLogo("partner-38")],["Winterhalter",normalizedLogo("partner-39")],["ITV Ice Makers",normalizedLogo("partner-40")],["Fiorini",normalizedLogo("partner-41")],["Chanmag",normalizedLogo("partner-42")],["Sinmag",normalizedLogo("partner-43")],["Kolb",normalizedLogo("partner-44")],["Berto's",normalizedLogo("profile-bertos")],["Nayati",normalizedLogo("profile-nayati")],["Sirman",normalizedLogo("profile-sirman")],["Kingcool",normalizedLogo("profile-kingcool")],["Aristarco",normalizedLogo("profile-aristarco"),true],["Halton",normalizedLogo("profile-halton")],["ANSUL",normalizedLogo("profile-ansul")],["Swastik Synergy",normalizedLogo("profile-swastik-synergy")]];
const clients=[["Shangri-La",normalizedLogo("client-3")],["Marriott",normalizedLogo("international-25")],["Sheraton",normalizedLogo("client-special-39")],["Cinnamon",normalizedLogo("client-2")],["Burger King",normalizedLogo("client-11")],["Domino's",normalizedLogo("client-12")]];

function AnchorHeader({base}:{base:string}){const links=[["home","Home"],["solutions","Solutions"],["projects-brands","Projects & Brands"],["about","About Us"],["contact-support","Contact & Support"]];return <header className="header country-header"><Link href="/" className="logo-link" aria-label="TGF Global home"><Logo/></Link><nav className="desktop-nav" aria-label="Page sections">{links.map(([id,label])=><a key={id} href={`${base}#${id}`}>{label}</a>)}</nav><a className="gold-btn header-cta" href={`${base}#contact-support`}>Discuss Your Project <span>→</span></a><details className="mobile-menu"><summary>Menu</summary><nav>{links.map(([id,label])=><a key={id} href={`${base}#${id}`}>{label}</a>)}</nav></details></header>}

export function CountryPage({country,globalLanding=false}:{country:CountryKey;globalLanding?:boolean}){const d=data[country];const market=countries.find(c=>c.key===country)!;const base=globalLanding?"/":market.route;const signature=globalLanding?"TGF Global":d.place;return <div className={`country-page country-${country}${globalLanding?" global-landing":""}`}><AnchorHeader base={base}/><main>
  <section id="home" className="proto-hero country-hero"><div className="proto-hero-copy">{globalLanding?<><span className="country-eyebrow">International foodservice expertise · Local market delivery</span><h1>Four markets.<br/>One vision.<br/><em>Engineered<br/>to perform.</em></h1><p>One foodservice solutions group connecting global standards with accountable local expertise across Sri Lanka, Bangladesh, Maldives and Dubai.</p><div className="global-market-list" aria-label="TGF markets"><span>Sri Lanka</span><span>Bangladesh</span><span>Maldives</span><span>Dubai</span></div><a className="gold-btn global-explore" href="#markets">Explore Our Markets <span>↓</span></a></>:<><span className="country-eyebrow">{d.eyebrow}</span><h1>{d.headline}</h1><p>{d.intro}</p></>}</div><div className={`country-signature ${globalLanding?"global-signature":"regional-signature"}`} aria-label={signature}>{globalLanding?<span className="signature-mark"><img src="/tgf-logo.png" alt="" aria-hidden="true"/></span>:<span className="signature-flag"><img src={market.flag} alt={`${market.name} flag`}/></span>}<span className="signature-copy"><b>{signature}</b><small>{globalLanding?"The Global Food Holding":"TGF Holdings · Regional Market"}</small></span></div></section>
  <section id="markets" className="proto-markets proto-wrap country-switcher"><div className="proto-rule-title"><span>Four countries. One standard of excellence.</span></div><div className="proto-market-grid">{countries.map((item,i)=>{const isActive=!globalLanding&&item.key===country;return <Link href={item.route} aria-current={isActive?"page":undefined} className={`proto-market market-${i+1} ${isActive?"current-market":""}`} key={item.key}><div className="market-symbol market-flag"><img src={item.flag} alt={`${item.name} flag`}/></div><b>{item.name}</b><span>Explore <i>→</i></span></Link>})}</div></section>
  <section className="fcsi-feature fcsi-feature-v2 proto-wrap" aria-labelledby="fcsi-title"><div className="fcsi-copy"><span className="country-eyebrow">Why choose TGF?</span><h2 id="fcsi-title">International standards.<br/><em>Local accountability.</em></h2><p>{country==="sri-lanka"?"The only Sri Lankan company with membership of Foodservice Consultants Society International.":"Regional foodservice expertise backed by membership of Foodservice Consultants Society International."}</p><div className="fcsi-proof"><span>Professional membership</span><b>FCSI · Asia Pacific</b></div></div><div className="fcsi-mark"><span>Recognised by</span><img src="/fcsi-asia-pacific.svg" alt="Foodservice Consultants Society International Asia Pacific"/></div></section>
  <section id="solutions" className="country-solutions proto-wrap"><div className="proto-rule-title"><span>End-to-end foodservice solutions</span></div><div className="country-service-grid">{services.map(([title,copy],i)=><article className="country-service-card" key={title}><div className={`service-photo service-photo-${i+1}`}/><div><i>{["◇","▦","❄","≋","◉"][i]}</i><h2>{title}</h2><p>{copy}</p><a href={`${base}#contact-support`}>›</a></div></article>)}</div></section>
  <section id="projects-brands" className="country-projects proto-wrap"><div className="proto-rule-title"><span>Premium projects</span></div><div className="country-project-grid">{d.projects.map(([title,place,image],i)=><article key={title}>{image?<img className="project-shot" src={image} alt={`${title} commercial kitchen project`}/>:<div className={`project-shot project-shot-${i+1}`}/>}<div><b>{title}</b><span>{place}</span></div></article>)}</div><a className="country-outline-btn" href={`${base}#contact-support`}>View All Projects <span>›</span></a><div className="proto-rule-title brand-heading"><span>Our partner brands</span></div><PartnerCarousel brands={partners}/><div className="proto-rule-title brand-heading"><span>Trusted by leading brands</span></div><div className="country-logo-row country-client-row">{clients.map(([name,src])=><div key={name}><img src={src} alt={name}/></div>)}</div></section>
  <section id="about" className="country-about proto-wrap"><div><span className="country-eyebrow">About TGF · {d.place}</span><h2>Engineering precision.<br/>Culinary purpose.</h2></div><p>The Global Food Holding is a Sri Lankan-based commercial kitchen equipment and solutions provider with overseas subsidiaries. TGF brings planning, design, supply, installation, workflow optimisation and after-sales care together to create efficient, safe, sustainable and future-ready foodservice environments.</p><div className="country-stats"><span><b>End-to-end</b>Planning to after-sales care</span><span><b>FCSI-aligned</b>Globally benchmarked standards</span><span><b>Local insight</b>Regional technical support</span></div></section>
  <section id="contact-support" className="country-support proto-wrap"><div className="country-support-icon">⚒</div><div><span className="country-eyebrow">Technical support</span><h2>Flavour is engineered.<br/>Performance is supported.</h2><p>Internationally trained expertise and dependable after-sales care throughout the equipment lifecycle.</p></div><a className="country-outline-btn" href="mailto:info@tgfholding.com">Discuss Your Project <span>›</span></a></section>
  </main><footer className="country-footer"><div className="country-footer-brand"><Logo/><p>Commercial kitchen equipment and foodservice solutions across Sri Lanka and overseas markets. At TGF, flavour is engineered.</p></div><div><b>Solutions</b><a href={`${base}#solutions`}>Planning & kitchen design</a><a href={`${base}#solutions`}>Equipment supply & installation</a><a href={`${base}#solutions`}>Workflow optimisation</a><a href={`${base}#solutions`}>After-sales support</a></div><div><b>Projects</b><a href={`${base}#projects-brands`}>Selected projects</a>{countries.map(c=><Link href={c.route} key={c.key}>{c.name}</Link>)}</div><div><b>Company</b><a href={`${base}#about`}>Who we are</a><a href={`${base}#about`}>Our approach</a><a href={`${base}#contact-support`}>Contact</a></div><div><b>Support</b><a href={`${base}#contact-support`}>Service & maintenance</a><a href={`${base}#contact-support`}>Technical support</a><a href="mailto:info@tgfholding.com">info@tgfholding.com</a><a href="tel:+94727568612">+94 727 568 612</a></div><p className="fineprint">© 2026 The Global Food Holding (TGF). All rights reserved.</p></footer></div>}
