import Link from "next/link";
import { Logo } from "./site-shell";

type CountryKey="sri-lanka"|"bangladesh"|"maldives"|"dubai";
const countries:{key:CountryKey;name:string;route:string;code:string}[]=[
  {key:"sri-lanka",name:"Sri Lanka",route:"/",code:"LK"},{key:"bangladesh",name:"Bangladesh",route:"/bangladesh",code:"BD"},
  {key:"maldives",name:"Maldives",route:"/maldives",code:"MV"},{key:"dubai",name:"Dubai",route:"/dubai",code:"AE"},
];
const data={
  "sri-lanka":{place:"Sri Lanka",eyebrow:"Sri Lanka commercial kitchen specialists",headline:<>Commercial<br/>kitchens.<br/><em>Engineered<br/>to perform.</em></>,intro:"TGF plans, designs, supplies, installs and supports future-ready foodservice environments for hospitality, healthcare, commercial and institutional operations.",projects:[["Hilton Yala","Complete FOH & BOH kitchen equipment","/project-hilton-yala.png"],["Hilton Colombo","Complete FOH & BOH kitchen equipment","/project-hilton-colombo.png"],["Hilton Weerawila","Design, supply & FOH installation","/project-hilton-weerawila.png"]]},
  bangladesh:{place:"Bangladesh",eyebrow:"Foodservice solutions for Bangladesh",headline:<>Hospitality<br/>kitchens.<br/><em>Built for<br/>scale.</em></>,intro:"Engineering-led planning, equipment supply, installation and long-term technical support for hospitality, healthcare, commercial and institutional foodservice.",projects:[["Hospitality kitchens","Bangladesh portfolio"],["Healthcare foodservice","Bangladesh portfolio"],["Commercial kitchens","Bangladesh portfolio"],["Institutional kitchens","Bangladesh portfolio"]]},
  maldives:{place:"Maldives",eyebrow:"Island hospitality expertise",headline:<>Resort<br/>kitchens.<br/><em>Designed for<br/>island life.</em></>,intro:"Globally benchmarked kitchen systems, dependable equipment and after-sales care tailored to remote island hospitality and resort operations.",projects:[["W Maldives","FOH & BOH kitchen equipment","/project-w-maldives.png"],["Le Méridien Maldives Resort & Spa","Complete FOH & BOH kitchen equipment","/project-le-meridien-maldives.png"]]},
  dubai:{place:"Dubai",eyebrow:"Commercial kitchens for the UAE",headline:<>High-performance<br/>kitchens.<br/><em>Ready for<br/>ambition.</em></>,intro:"Technically rigorous, efficient and future-ready foodservice solutions shaped around the operational demands of the UAE hospitality market.",projects:[["Hospitality kitchens","UAE portfolio"],["Healthcare foodservice","UAE portfolio"],["Commercial kitchens","UAE portfolio"],["Institutional kitchens","UAE portfolio"]]},
} as const;
const services=[["Planning & kitchen design","FCSI-aligned planning shaped around workflow, ergonomics, safety and operational efficiency."],["Equipment supply & installation","Globally reputed equipment specified, supplied and installed for reliable long-term performance."],["Fabrication & infrastructure","Commercial kitchen fabrication and infrastructure solutions engineered for real operating conditions."],["Workflow optimisation","Future-ready systems that integrate equipment, technology and sustainable operational practices."],["After-sales support","Internationally trained technical expertise providing dependable service throughout the equipment lifecycle."]];
const partners=[["UNOX","/logos/partner-32.jpg"],["Williams","/logos/partner-33.jpg"],["Precision","/logos/partner-34.jpg"],["Hobart","/logos/partner-35.jpg"],["Sammic","/logos/partner-36.jpg"],["Roller Grill","/logos/partner-37.jpg"]];
const clients=[["Shangri-La","/logos/client-3.png"],["Marriott","/logos/international-25.jpg"],["Sheraton","/logos/client-special-39.png"],["Cinnamon","/logos/client-2.png"],["Burger King","/logos/client-11.png"],["Domino's","/logos/client-12.png"]];

function AnchorHeader({base}:{base:string}){const links=[["home","Home"],["solutions","Solutions"],["projects-brands","Projects & Brands"],["about","About Us"],["contact-support","Contact & Support"]];return <header className="header country-header"><Link href={`${base}#home`} className="logo-link"><Logo/></Link><nav className="desktop-nav" aria-label="Page sections">{links.map(([id,label])=><a key={id} href={`${base}#${id}`}>{label}</a>)}</nav><a className="gold-btn header-cta" href={`${base}#contact-support`}>Discuss Your Project <span>→</span></a><details className="mobile-menu"><summary>Menu</summary><nav>{links.map(([id,label])=><a key={id} href={`${base}#${id}`}>{label}</a>)}</nav></details></header>}

export function CountryPage({country}:{country:CountryKey}){const d=data[country];const base=countries.find(c=>c.key===country)!.route;return <div className={`country-page country-${country}`}><AnchorHeader base={base}/><main>
  <section id="home" className="proto-hero country-hero"><div className="proto-hero-copy"><span className="country-eyebrow">{d.eyebrow}</span><h1>{d.headline}</h1><p>{d.intro}</p><a className="gold-btn" href={`${base}#contact-support`}>Discuss Your Project <span>→</span></a></div><span className="country-signature" aria-label={`TGF ${d.place}`}><img src="/tgf-logo.png" alt="" aria-hidden="true"/> {d.place}</span></section>
  <section className="proto-markets proto-wrap country-switcher"><div className="proto-rule-title"><span>Four countries. One standard of excellence.</span></div><div className="proto-market-grid">{countries.map((item,i)=><Link href={item.route} aria-current={item.key===country?"page":undefined} className={`proto-market market-${i+1} ${item.key===country?"current-market":""}`} key={item.key}><div className="market-symbol">{item.code}</div><b>{item.name}</b><span>→</span></Link>)}</div></section>
  <section id="solutions" className="country-solutions proto-wrap"><div className="proto-rule-title"><span>End-to-end foodservice solutions</span></div><div className="country-service-grid">{services.map(([title,copy],i)=><article className="country-service-card" key={title}><div className={`service-photo service-photo-${i+1}`}/><div><i>{["◇","▦","❄","≋","◉"][i]}</i><h2>{title}</h2><p>{copy}</p><a href={`${base}#contact-support`}>›</a></div></article>)}</div></section>
  <section id="projects-brands" className="country-projects proto-wrap"><div className="proto-rule-title"><span>Premium projects</span></div><div className="country-project-grid">{d.projects.map(([title,place,image],i)=><article key={title}>{image?<img className="project-shot" src={image} alt={`${title} commercial kitchen project`}/>:<div className={`project-shot project-shot-${i+1}`}/>}<div><b>{title}</b><span>{place}</span></div></article>)}</div><a className="country-outline-btn" href={`${base}#contact-support`}>View All Projects <span>›</span></a><div className="proto-rule-title brand-heading"><span>Our partner brands</span></div><div className="country-logo-row">{partners.map(([name,src])=><div key={name}><img src={src} alt={name}/></div>)}</div><div className="proto-rule-title brand-heading"><span>Trusted by leading brands</span></div><div className="country-logo-row country-client-row">{clients.map(([name,src])=><div key={name}><img src={src} alt={name}/></div>)}</div></section>
  <section id="about" className="country-about proto-wrap"><div><span className="country-eyebrow">About TGF · {d.place}</span><h2>Engineering precision.<br/>Culinary purpose.</h2></div><p>The Global Food Holding is a Sri Lankan-based commercial kitchen equipment and solutions provider with overseas subsidiaries. TGF brings planning, design, supply, installation, workflow optimisation and after-sales care together to create efficient, safe, sustainable and future-ready foodservice environments.</p><div className="country-stats"><span><b>End-to-end</b>Planning to after-sales care</span><span><b>FCSI-aligned</b>Globally benchmarked standards</span><span><b>Local insight</b>Regional technical support</span></div></section>
  <section className="fcsi-feature fcsi-feature-v2 proto-wrap" aria-labelledby="fcsi-title"><div className="fcsi-copy"><span className="country-eyebrow">Why choose TGF?</span><h2 id="fcsi-title">International standards.<br/><em>Local accountability.</em></h2><p>{country==="sri-lanka"?"The only Sri Lankan company with membership of Foodservice Consultants Society International.":"Regional foodservice expertise backed by membership of Foodservice Consultants Society International."}</p><div className="fcsi-proof"><span>Professional membership</span><b>FCSI · Asia Pacific</b></div></div><div className="fcsi-mark"><span>Recognised by</span><img src="/fcsi-asia-pacific.svg" alt="Foodservice Consultants Society International Asia Pacific"/></div></section>
  <section id="contact-support" className="country-support proto-wrap"><div className="country-support-icon">⚒</div><div><span className="country-eyebrow">Technical support</span><h2>Flavour is engineered.<br/>Performance is supported.</h2><p>Internationally trained expertise and dependable after-sales care throughout the equipment lifecycle.</p></div><a className="country-outline-btn" href="mailto:info@tgfholding.com">Discuss Your Project <span>›</span></a></section>
  </main><footer className="country-footer"><div className="country-footer-brand"><Logo/><p>Commercial kitchen equipment and foodservice solutions across Sri Lanka and overseas markets. At TGF, flavour is engineered.</p></div><div><b>Solutions</b><a href={`${base}#solutions`}>Planning & kitchen design</a><a href={`${base}#solutions`}>Equipment supply & installation</a><a href={`${base}#solutions`}>Workflow optimisation</a><a href={`${base}#solutions`}>After-sales support</a></div><div><b>Projects</b><a href={`${base}#projects-brands`}>Selected projects</a>{countries.map(c=><Link href={c.route} key={c.key}>{c.name}</Link>)}</div><div><b>Company</b><a href={`${base}#about`}>Who we are</a><a href={`${base}#about`}>Our approach</a><a href={`${base}#contact-support`}>Contact</a></div><div><b>Support</b><a href={`${base}#contact-support`}>Service & maintenance</a><a href={`${base}#contact-support`}>Technical support</a><a href="mailto:info@tgfholding.com">info@tgfholding.com</a><a href="tel:+94727568612">+94 727 568 612</a></div><p className="fineprint">© 2026 The Global Food Holding (TGF). All rights reserved.</p></footer></div>}
